---
- name: Build Portfolio Docker Image on Target VMs
  hosts: all
  become: yes
  tasks:
    - name: Ensure project directory exists on targets
      ansible.builtin.file:
        path: /opt/portfolio-app
        state: directory
        mode: '0755'

    - name: copy ALL Files
      ansible.builtin.copy:
        src: webapp/
        dest: /opt/portfolio-app/
        mode: '0755'

    - name: Copy Dockerfile to target VMs
      ansible.builtin.copy:
        src: dockerfile
        dest: /opt/portfolio-app/Dockerfile

    - name: Build Docker image
      community.docker.docker_image:
        name: portfolio-app
        build:
          path: /opt/portfolio-app
        source: build
        state: present