---
- name: Run Portfolio Docker Container
  hosts: all
  become: yes
  tasks:
    - name: Start portfolio container
      community.docker.docker_container:
        name: portfolio-web
        image: portfolio-app
        state: started
        recreate: yes
        ports:
          - "8080:80"
        restart_policy: always