---
# tasks file for Web-Servers


  - name: install updates (Ubuntu)  
    tags: always
    apt:  
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"  



  - name: Install apache and php for Ubuntu Servers
    apt: 
      name:
         - apache2 
         - libapache2-mod-php 
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for CentOS Servers
    tags: apache,centos,httpd
    dnf:
      name:
         - httpd
         - php    
      state: latest
    when: ansible_distribution == "CentOS"
